4.40/Nop.Plugin.Widgets.PowerReviews/Controllers/PowerReviewsController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Widgets.PowerReviews.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System.Threading.Tasks;

namespace Nop.Plugin.Widgets.PowerReviews.Controllers
{
    public class PowerReviewsController : BasePluginController
    {
        private readonly PowerReviewsSettings _settings;
        private readonly ISettingService _settingService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;

        public PowerReviewsController(PowerReviewsSettings settings,
            ISettingService settingService,
            ILocalizationService localizationService,
            INotificationService notificationService
        )
        {
            _settings = settings;
            _settingService = settingService;
            _localizationService = localizationService;
            _notificationService = notificationService;
        }

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        [AutoValidateAntiforgeryToken]
        public ActionResult Configure()
        {
            return View(
                "~/Plugins/Widgets.PowerReviews/Views/Configure.cshtml",
                _settings.ToModel());
        }

        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Configure(PowerReviewsConfigModel model)
        {
            if (!ModelState.IsValid)
            {
                return Configure();
            }

            await _settingService.SaveSettingAsync(PowerReviewsSettings.FromModel(model));

            _notificationService.SuccessNotification(
                await _localizationService.GetResourceAsync("Admin.Plugins.Saved")
            );

            return Configure();
        }

        public IActionResult WriteAReview()
        {
            return View("~/Plugins/Widgets.PowerReviews/Views/WriteAReview.cshtml");
        }
    }
}

4.40/Nop.Plugin.Widgets.PowerReviews/Views/Configure.cshtml
@model Nop.Plugin.Widgets.PowerReviews.Models.PowerReviewsConfigModel

@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="PowerReviews" asp-action="Configure" method="post">
	<section class="content">
		<div class="container-fluid">			
				<div class="card card-default">
					<div class="card-body">
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="APIKey" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="APIKey" />
								<span asp-validation-for="APIKey"></span>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="MerchantGroupId" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="MerchantGroupId" />
								<span asp-validation-for="MerchantGroupId"></span>
							</div>
						</div>
                        <div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="MerchantId" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="MerchantId" />
								<span asp-validation-for="MerchantId"></span>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="ProductListingWidgetZone" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="ProductListingWidgetZone" />
								<span asp-validation-for="ProductListingWidgetZone"></span>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="ProductDetailWidgetZone" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="ProductDetailWidgetZone" />
								<span asp-validation-for="ProductDetailWidgetZone"></span>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="ProductDetailReviewsWidgetZone" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="ProductDetailReviewsWidgetZone" />
								<span asp-validation-for="ProductDetailReviewsWidgetZone"></span>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="CustomStyles" />
							</div>
							<div class="col-md-9">
								<nop-textarea asp-for="CustomStyles" />
								<span asp-validation-for="CustomStyles"></span>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="OnReadReviewsClickCode" />
							</div>
							<div class="col-md-9">
								<nop-textarea asp-for="OnReadReviewsClickCode" />
								<span asp-validation-for="OnReadReviewsClickCode"></span>
							</div>
						</div>
						<div class="form-group row">
                            <div class="col-md-9 offset-md-3">
                                <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                            </div>
						</div>
					</div>
				</div>			
		</div>
	</section>
</form>

4.40/Nop.Plugin.Widgets.PowerReviews/Views/Detail.cshtml
<div id="pr-reviewsnippet"></div>

4.40/Nop.Plugin.Widgets.PowerReviews/Views/DetailReviews.cshtml
<div id="pr-reviewdisplay"></div>

4.40/Nop.Plugin.Widgets.PowerReviews/Views/DetailScript.cshtml
@using Nop.Plugin.Widgets.PowerReviews.Models;
@using Nop.Core;

@inject IWebHelper webHelper

@model DetailModel

@{
    Html.AddHeadCustomParts("<script src=\"https://ui.powerreviews.com/stable/4.1/ui.js\" async></script>");
}

<script type="text/javascript">
	window.pwr = window.pwr || function () {
  		(pwr.q = pwr.q || []).push(arguments);
	}; 
 	
	pwr("render", {
		api_key: '@Model.Settings.APIKey',
		locale: 'en_US',
		merchant_group_id: '@Model.Settings.MerchantGroupId',
		merchant_id: '@Model.Settings.MerchantId',
		page_id: "@Model.ProductSku",
		review_wrapper_url: '/write-a-review?pr_page_id=@Model.ProductSku',
		on_read_reviews_click: function () {
			@Html.Raw(Model.Settings.OnReadReviewsClickCode)
		},
		product:{
            name: '@Model.FeedlessProduct.Name',
            url: '@Model.FeedlessProduct.Url',
            image_url: '@Model.FeedlessProduct.ImageUrl',
            description: '@Model.FeedlessProduct.Description',
            category_name: '@Model.FeedlessProduct.CategoryName',
            manufacturer_id: '@Model.FeedlessProduct.ManufacturerId',
            upc: '@Model.FeedlessProduct.Upc',
            brand_name: '@Model.FeedlessProduct.BrandName',
            price: '@Model.FeedlessProduct.Price',
            in_stock: '@Model.FeedlessProduct.InStock'
   		},
		subject: {
			"@@context": "https://schema.org",
			"@@type": "Product",
			name: "@Model.FeedlessProduct.Name",
			description: "@Model.FeedlessProduct.Description",
			url: "@Model.FeedlessProduct.Url",
			image: "@Model.FeedlessProduct.ImageUrl",
			sku: "@Model.ProductSku",
			brand: "@Model.FeedlessProduct.BrandName",
			upc: '@Model.FeedlessProduct.Upc',
			offers: {
				"@@type": "Offer",
				priceCurrency: "USD",
				url: "@Model.FeedlessProduct.Url",
				price: "@Model.FeedlessProduct.Price",
				priceValidUntil: "@Model.PriceValidUntil.ToShortDateString()",
				availability: "https://schema.org/InStock"
			}
		},	
		components: {
			ReviewSnippet: 'pr-reviewsnippet',
			ReviewDisplay: 'pr-reviewdisplay'
		}
	});
</script>

<style>
	@Html.Raw(Model.Settings.CustomStyles)
</style>

4.40/Nop.Plugin.Widgets.PowerReviews/Views/Listing.cshtml
@using Nop.Plugin.Widgets.PowerReviews.Models

@model ListingModel


<div id="pr_snippet_product_@Model.ProductId">
  <span style="display: none" class="product-box-sku">@Model.ProductSku</span>
</div>

4.40/Nop.Plugin.Widgets.PowerReviews/Views/ListingScript.cshtml
@using Nop.Plugin.Widgets.PowerReviews

@model PowerReviewsSettings

@{
	Html.AppendScriptParts("~/lib_npm/jquery/jquery.min.js");
    Html.AddHeadCustomParts("<script src=\"https://ui.powerreviews.com/stable/4.1/ui.js\" async></script>");
}

<script>
	var currentlyDisplayedPrSnippets = [];

	$(document).ready(function () {
		updatePowerReviewsCategorySnippets()

		$(document).ajaxComplete(function( event,request, settings ) {
			updatePowerReviewsCategorySnippets()
		});
	});

	function updatePowerReviewsCategorySnippets() {
		var productGrid = $('.product-grid');
		if (productGrid.length == 0 || productGrid.is(":hidden")) {	return;	}

		var prSnippets = productGrid.find("[id^='pr_snippet_product_']");
		if (areArraysEqual(prSnippets, currentlyDisplayedPrSnippets)) {	return;	}

		currentlyDisplayedPrSnippets = prSnippets;

		var powerReviewsRenderConfigs = [];
		prSnippets.each(function(index, item){
			var sku = $(item).find('.product-box-sku').text().replace(/[^0-9a-zA-Z-]/gi,'');

			powerReviewsRenderConfigs.push({
				page_id: sku,
				api_key: "@Model.APIKey",
				locale: "en_US",
				merchant_group_id: "@Model.MerchantGroupId",
				merchant_id: "@Model.MerchantId",
				review_wrapper_url: `/write-a-review?pr_page_id={sku}`,
				ENABLE_CLIENT_SIDE_STRUCTURED_DATA: false,
				components: {
					CategorySnippet: prSnippets[index].id
				}
			});
		});		

		window.pwr = window.pwr || function () {
			(pwr.q = pwr.q || []).push(arguments); 
		};
		pwr("render", powerReviewsRenderConfigs);
	}

    function areArraysEqual(a1, a2) {
		if (a1.length !== a2.length) {
			return false;
		}
		for (var i = a1.length; i--;) {
			if (a1[i] !== a2[i]) {
				return false;
			}
		}
		return true;
	}
</script>

<style>
	@Html.Raw(Model.CustomStyles)
</style>

4.40/Nop.Plugin.Widgets.PowerReviews/Views/WriteAReview.cshtml
@using Nop.Core
@using Nop.Plugin.Widgets.PowerReviews

@inject PowerReviewsSettings powerReviewsSettings
@inject IWebHelper webHelper

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";
}

<div id="pr-write"></div>
<script src="https://ui.powerreviews.com/stable/4.1/ui.js" async></script>
      
<script>
    window.pwr = window.pwr || function () {
       (pwr.q = pwr.q || []).push(arguments); 
    };
    pwr("render", {
      api_key: '@powerReviewsSettings.APIKey',
      locale: 'en_US',
      merchant_group_id: '@powerReviewsSettings.MerchantGroupId',
      merchant_id: '@powerReviewsSettings.MerchantId',
      style_sheet: '@webHelper.GetStoreLocation()Plugins/Widgets.PowerReviews/styles/pr-war-styles.css',
      on_submit: function(config, data){
        window.scrollTo(0,0); 
      },
      components: {
        Write: 'pr-write'
      }
    });
</script>